### ISSUE TITLE
Station Names

### ISSUE THREAD

**Issue by themightymanuel** [esi/esi-issues#315] opened 2017-03-14 18:16 UTC
Is the only way to get the name of a station from its ID by first deciding if the ID is a player station or a NPC station then make a request to either 
/v2/universe/stations/{station_id}/
/v1/universe/structures/{structure_id}/
And what if I want the name of a player station I do not have access to? I don't need the X,Y,Z coordinates just the name and system. Alternatively could the market order endpoint return this information similar to crest?

**Comment by Blacksmoke16** [comment] 2017-03-18 02:17
If the id of the station/structure in question is greater than 1_000_000_000_000 then it is a citadel.  Else it is a station.

Really as of now, there is no ESI way to get the name of a structure if you can't dock there anyway; as if you can't dock there it doesn't show up in search.  The only way to know is if someone links it to you or read it when you are in the same system.  Since getting the name of the structure includes the system of it it kinda defeats the purpose of it not showing up in the search list.

**Comment by lukasni** [comment] 2020-02-18 19:59
Closing this since `system_id` has been added to ranged market orders and the names of inaccessible structures not being available is by design.

**Closed by lukasni** 2020-02-18 19:59 UTC
Labels: esi-universe, feature request
