### ISSUE TITLE
Get dogma attribute and unit_id

### ISSUE THREAD

**Issue by biow0lf** [esi/esi-issues#1270] opened 2021-02-12 16:25 UTC
# Bug

Dogma Attribute endpoint return `unit_id` in response. But, ESI missing `units` endpoint to get this info.

In last SDE release this information missing too.

MD5 sum of this SDE release: `9aadb21edd23f8ffaed5519ec2317fc3`

So, where we can get this info now?

## Request

`https://esi.evetech.net/dev/dogma/attributes/4/?datasource=tranquility`

### Status Code

`200`

### Headers

```
access-control-allow-credentials: true 
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
access-control-allow-methods: GET,HEAD,OPTIONS 
access-control-allow-origin: * 
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
access-control-max-age: 600 
allow: GET,HEAD,OPTIONS 
cache-control: public 
content-length: 190 
content-type: application/json; charset=UTF-8 
date: Fri, 12 Feb 2021 16:18:36 GMT 
etag: W/"0dc2e8f52d36a3de964a59bc3a68c32bb56d43470baa3ed26272d62c" 
expires: Sat, 13 Feb 2021 11:05:00 GMT 
last-modified: Fri, 12 Feb 2021 11:02:02 GMT 
strict-transport-security: max-age=31536000 
x-esi-error-limit-remain: 100 
x-esi-error-limit-reset: 24 
x-esi-request-id: 8b9e2708-3505-4b03-a74e-02645c3fe090
```

### Body

```json
{
  "attribute_id": 4,
  "default_value": 0,
  "description": "Integer that describes the types mass",
  "display_name": "Mass",
  "high_is_good": true,
  "icon_id": 76,
  "name": "mass",
  "published": true,
  "unit_id": 2
}
```

## Expected

Place where to get `units` info.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by Blacksmoke16** [comment] 2021-02-12 16:27
Duplicate of https://github.com/esi/esi-issues/issues/404.

**Closed by Blacksmoke16** 2021-02-12 16:27 UTC

**Comment by biow0lf** [comment] 2021-02-12 16:32
Can anyone ping CCP about that? They are just remove `sde/bsd/eveUnits.yaml` from latest SDE release.

I don't know where to report this.

**Comment by Blacksmoke16** [comment] 2021-02-12 16:35
@biow0lf IIRC SDE issues should be made as bug reports.  But maybe someone else from @esi/ecm has more information on that.

**Comment by CarbonAlabel** [comment] 2021-02-12 16:58
The lack of a proper place to report SDE issues is an issue by itself, as acknowledged by CCP.
