### ISSUE TITLE
Fetch Citadel Market orders similar to NPC Stations

### ISSUE THREAD

**Issue by alentoghostflame** [esi/esi-issues#1201] opened 2020-05-07 16:20 UTC
# Feature Request

It would be nice if there was a way to quickly get the market orders of all market-capable Citadels in a region, very similar to `/markets/{region_id}/orders`.
Preferably, it would be integrated into `/markets/{region_id}/order`, no token giving you NPC markets, token giving you NPC and Citadel.

## Use case

Anyone wanting to get all market orders in an area, including citadels.

## Authentication

`esi-markets.structure_markets` should be reusable for this.

## Example return

Exactly like what `/markets/{region_id}/orders/`returns currently.

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by Dusty-Meg** [comment] 2020-05-07 16:24
This was an explicit design choice to not happen which is explained [Here](https://github.com/esi/esi-issues/issues/826#issuecomment-384686625)

**Comment by Blacksmoke16** [comment] 2020-05-07 16:25
Duplicate of https://github.com/esi/esi-issues/issues/826

**Closed by Blacksmoke16** 2020-05-07 16:25 UTC
Labels: duplicate, esi-markets
