### ISSUE TITLE
/universe/ids/ returning incorrectly

### ISSUE THREAD

**Issue by fuzzysteve** [esi/esi-issues#850] opened 2018-04-18 16:59 UTC
# Bug
ESI endpoint /universe/id for request body [“Jita”] does not return system id. It only returns an alliance including “Jita” in its name.

### Request

curl -X POST "https://esi.tech.ccp.is/latest/universe/ids/" -H  "accept: application/json" -H  "Content-Type: application/json" -d "[  \"Jita\"]"

### Response

{   "alliances": [     {       "id": 99005382,       "name": "Jita Holding Inc."     }   ] }

### Expected

{   "solarsystems": [     {       "id": 30000142,       "name": "Jita"     }   ] }

**Comment by DaneelTrevize** [comment] 2018-04-18 17:54
Probably highly related to #806

**Comment by ccp-zoetrope** [comment] 2018-08-03 14:09
Closing as duplicate of https://github.com/esi/esi-issues/issues/806

**Closed by ccp-zoetrope** 2018-08-03 14:09 UTC
Labels: bug, esi-universe
