### ISSUE TITLE
Request: Get current waypoints

### ISSUE THREAD

**Issue by drucifer** [esi/esi-issues#919] opened 2018-05-14 18:04 UTC
# Feature Request
It would be helpful to be able to get a list of currently set waypoints.

I would imagine this being implemented as a GET method on the existing /ui/autopilot/waypoint/ POST endpoint.

## Use case
1. In some cases it would not be necessary (and would cause an error) to set a new waypoint if the waypoint is already set.  It would be helpful for apps to be able to detect this condition in advance of attempting to set a new waypoint.
2. Would allow features that could compare certain region dependent information between the current location and destination, e.g. market orders on watched items for a hauling focused app.
3. Would allow "reminder" features, e.g. if your current ship is heavy on explosive mitigation and you are leaving Minmatar / Angel space and headed towards Gallente / Serpentis, a PVE focused app could recommend swapping to thermal mitigation.

## Authentication
Authentication is required as this data is specific to the current user's UI.

There is an existing esi-ui.write_waypoint.v1.  Following the convention used by other endpoints, this would need a new scope such as:
esi-ui.read_waypoint.v1

## Example return
```json
[
    30002771,
    30002770,
    30002769,
    30002772
 ]
```

# Checklist
Check all boxes that apply to this issue:

- [X] Feature request description is provided
- [X] Use case exists
- [X] Feature requires a new route
- [ ] Feature adds data to existing route
- [X] Feature requires new auth scope
- [ ] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by CarbonAlabel** [comment] 2018-05-17 14:18
Duplicate of #366.

**Closed by CarbonAlabel** 2018-05-17 14:18 UTC
Labels: esi-ui, feature request
