### ISSUE TITLE
Fleet endpoint errors show tmi

### ISSUE THREAD

**Issue by Flupster** [esi/esi-issues#1113] opened 2019-04-13 08:21 UTC
# Bug

It appears errors are handled differently or incorrectly in the fleets endpoint see examples below

## Request

`GET /latest/fleets/123?token=a_fake_token`
`GET /latest/fleets/123?token=a_real_token`

### Status Code

`403` / `520`

### Body

```json
{
  "error": "{'error_label': 'UnMachoDestination', 'error_dict': {'what': 'The specified proxy or server node (123) is dead'}}"
}
```
```json
{
  "error": "invalid character '<' looking for beginning of value",
  "sso_status": 401
}
```

## Expected

Uniform errors?

**Comment by CarbonAlabel** [comment] 2019-04-14 21:54
The 403 is described in https://github.com/esi/esi-issues/issues/1055, the 520 might be worth a closer look.

Care to elaborate on what your expectation of "Uniform errors" is supposed to mean?

**Comment by Flupster** [comment] 2019-04-14 21:57
> The 403 is described in #1055, the 520 might be worth a closer look.
> 
> Care to elaborate on what your expectation of "Uniform errors" is supposed to mean?

Generally ESI issues are:

```JSON
{"error": "fleet does not exist"}
```
and not JSON strings, that should be fairly obvious...

**Comment by CarbonAlabel** [comment] 2019-04-14 22:25
It's really not that obvious. Context matters.

So the issue is that fleets that have been closed/don't exist will return a 520 error instead of an more appropriate 40x error?

**Comment by tsuthers-ccpgames** [comment] 2019-04-15 11:33
Yeah, it's because fleets are routed to nodes deterministically based on their ID, so if you request one that doesn't exist you usually get routed to a node that doesn't exist. That should be more robust.

**Comment by tsuthers-ccpgames** [comment] 2019-05-09 10:21
I've submitted a fix for the fake fleet ID returning internal monolith errors, it'll return a more standard 404. That code's checked into the next release branch and it'll trickle out later this month I think.

Discussion on the error codes from invalid tokens should happen in #1055

**Comment by tsuthers-ccpgames** [comment] 2019-05-27 19:45
Turns out this is really finicky and there's some kind of problem with the fix on sisi that causes it to error under other circumstances that I haven't nailed down yet.

I'm going to roll back the fix for this and try again later but unfortunately due to how late this was caught it's possible that there's going to be major problems with the fleet endpoints for 24h tomorrow, sorry everyone :(

**Comment by Xamber** [comment] 2020-11-05 13:08
Should be fixed, If no - please open again ❤️

**Closed by Xamber** 2020-11-05 13:08 UTC
Labels: bug, esi-fleets
