### ISSUE TITLE
Add a Bulk POST Endpoint for Getting Groups and Market Groups from Type IDs

### ISSUE THREAD

**Issue by 1adog1** [esi/esi-issues#1193] opened 2020-04-11 18:42 UTC
# Feature Request

This would basically be an Affiliations-Style endpoint for Type IDs, where users could bulk-request Group and Market Group (if applicable) IDs for a large amount of items. 

## Use case

Basically anyone working with a large amount of types, including but not limited to Market/Contract Tools, D-Scan Tools, and Asset Tools. 

## Authentication

Public Route. No Auth Required. 

## Example return

```json
[
  {
    "type_id": 583,
    "group_id": 25,
    "market_group_id": 61
  },
  ...999 Other Types
]
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [x] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [ ] Feature can reuse existing scope
- [x] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by rayanth** [comment] 2020-04-11 21:26
Groups and Market Groups are extremely static for a given typeID... Don't think they ever really change. So I see little use-case for this - copy the Groups and Market Groups to a local copy, or use SDE, and then any time a new item comes out you just query it from /universe/types, and add its groups to your local cache? What am I missing?

**Comment by 1adog1** [comment] 2020-04-12 00:12
The same argument could be applied to the `/universe/ids/` and `/universe/names/` endpoints, but ultimately people still use those over Static Data because it's one less thing to worry about updating, and cleaner to work with.

**Comment by CarbonAlabel** [comment] 2020-04-12 00:36
The affiliations endpoint, along with the names and IDs endpoints (which are esentially bulk search), are very much special cases. Among other things, they deal with player entity data that changes live and rapidly. Bulk endpoints for static data are not how ESI currently does things: If you are able to, just make however many thousand requests you need to.

Closing as duplicate of https://github.com/esi/esi-issues/issues/1001

**Closed by CarbonAlabel** 2020-04-12 00:36 UTC
