### ISSUE TITLE
Expose the indices that make up the Activity Defense Multiplier for systems 

### ISSUE THREAD

**Issue by StephenSwat** [esi/esi-issues#167] opened 2016-12-20 16:55 UTC
The ADM of systems is made up of three different values (strategic, military and industrial) but we can currently only access the ADM itself and not the constituent parts. Getting the ADM for a system is, in itself, also somewhat more complicated that it perhaps should be as one needs to find a sovereignty structure in the `/sovereignty/structures/` endpoint in the right system first.

Please allow us to get the ADM and its constituent parts with some ESI endpoint.

**Comment by StephenSwat** [comment] 2016-12-22 16:21
To add to this, it seems the `/sovereignty/structures/` is very out of date. It takes a long time to catch up to the in-game values.

**Comment by ErikKalkoken** [comment] 2020-04-15 12:53
Looks to me like this issue is a duplicate of https://github.com/esi/esi-issues/issues/655

**Comment by Blacksmoke16** [comment] 2020-04-15 12:57
Duplicate of #655

**Closed by Blacksmoke16** 2020-04-15 12:57 UTC
Labels: duplicate, esi-sovereignty, feature request
