### ISSUE TITLE
Old/Incorrect solar system ID returned from Character Location

### ISSUE THREAD

**Issue by Slazanger** [esi/esi-issues#1033] opened 2018-09-10 16:33 UTC
# Bug

The Character Location api is returning the incorrect system. It appears to be the system I was in at downtime

## Request

`GET /v1/characters/xxxxx/location?datasource=tranquility`

## Response

OK

### Status Code

`200`

### Headers

X-Esi-Request-Id: 73fb4945-fdb5-4a14-a655-b6a566d3717d
Date: Mon, 10 Sep 2018 16:25:00 GMT
Last-Modified: Mon, 10 Sep 2018 16:25:00 GMT

### Body

```json
{
	"solar_system_id":xxxxxxx,
	"structure_id":yyyyyy
}
```

## Expected

This is returning the system I was in at downtime, I've since moved a few systems over and have docked in another structure; however this hasnt been updated

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by ddavaham** [comment] 2018-09-10 16:55
Can you please provide "snapshots". For example, make the request, then login and move a couple of jumps, and make the request again. This endpoint has an incredibly short cache timer and this may just be a fluke. I just tested this myself with on a JF pilot and the endpoint updated the solar system id and station id immediately after the cache expired.

Include whatever details you feel comfortable providing, bare minimum being the request id as you did with this request.

**Comment by Slazanger** [comment] 2018-09-10 17:51
This is occurring on 1 of the 3 characters I've tested; and has been occurring since just after down time today..

Another request :
X-Esi-Request-Id: 082e5baa-6a93-4d32-9088-d2b117e78492

**Comment by Slazanger** [comment] 2018-09-10 17:56
And Jumped a System over again.. and its still not updated

X-Esi-Request-Id: dbcde203-0f85-4e9c-ac13-657db7caa2fc

**Comment by ddavaham** [comment] 2018-09-10 17:58
Thanka Sir. This will be a perfect example for the Devs

**Comment by ddavaham** [comment] 2018-09-13 05:17
Duplicate of https://github.com/esi/esi-issues/issues/828

**Closed by ddavaham** 2018-09-13 05:17 UTC
Labels: bug, duplicate, esi-location
