### ISSUE TITLE
Ship name sometimes includes unicode prefix

### ISSUE THREAD

**Issue by Ionaru** [esi/esi-issues#1204] opened 2020-05-12 10:57 UTC
# Bug

The `ship_name` from https://esi.evetech.net/v1/characters/{character_id}/ship/ sometimes includes a `u` prefix.

## Request

`GET https://esi.evetech.net/v1/characters/91347878/ship/`

### Status Code

`200`

### Headers

```
Content-Type: application/json; charset=UTF-8
Date: Tue, 12 May 2020 10:59:00 GMT
Expires: Tue, 12 May 2020 10:59:05 GMT
Last-Modified: Tue, 12 May 2020 10:59:00 GMT
X-ESI-Request-ID: b54e1a0a-8437-49e2-81d4-86ca9352c266
ETag: "3b1eeb3781812d9d9560748bec018f5413e5581bf84812562c4edf34"
```

### Body

```json
{
   "ship_item_id":1020345697671,
   "ship_name":"u'Shadow'",
   "ship_type_id":12735
}
```

![image](https://user-images.githubusercontent.com/3472373/81676216-e85da580-944f-11ea-977a-cf3b0a031b1d.png)

## Expected

```json
{
   "ship_item_id":1020345697671,
   "ship_name":"Shadow",
   "ship_type_id":12735
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by Ionaru** [comment] 2020-05-12 10:57
Maybe related to #1194.

**Comment by w9jds** [comment] 2020-05-12 22:17
Yes, this is a duplicate of #1194 as it isn't 100% consistent but the way data is stored to the database seems to be badly handled since they tried to remove unicode ship names without telling anyone...

**Comment by Blacksmoke16** [comment] 2020-05-12 22:19
Duplicate of https://github.com/esi/esi-issues/issues/1194.

**Closed by Blacksmoke16** 2020-05-12 22:19 UTC
Labels: bug, esi-characters
