### ISSUE TITLE
missing webifier effect of universe/types/webifierID

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#1200] opened 2020-05-05 23:22 UTC
# Bug

the ESI information for most statiswebifiers misses the effect to actually reduce target speed

I also checked [stasis grappler II](https://esi.evetech.net/latest/universe/types/41057) and it misses the same kind of effect. I checked in the sde and the only type with that effect is the [Naiyon's Modified Stasis Webifier](https://esi.evetech.net/latest/universe/types/15419)

## Request

https://esi.evetech.net/latest/universe/types/527 
(for example)

## Response

The network is no issue. The data is : 

```
"dogma_effects":[
{"effect_id":13,"is_default":false},
{"effect_id":16,"is_default":false},
{"effect_id":3174,"is_default":false},
{"effect_id":6426,"is_default":true}
]
```

## Expected

I expected the effect [decreaseTargetSpeed](https://esi.evetech.net/latest/dogma/effects/586) to appear in the list of effects of the type, just like it does for module [Naiyon's Modified Stasis Webifier](https://esi.evetech.net/latest/universe/types/15419) : 

```
"dogma_effects":[
{"effect_id":13,"is_default":false},
{"effect_id":16,"is_default":false},
{"effect_id":586,"is_default":true},
{"effect_id":3174,"is_default":false},
{"effect_id":6426,"is_default":true}
]
```

# Checklist

Check all boxes that apply to this issue:

- [ ] Bug description is provided
- [ ] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by gitAskur** [comment] 2020-11-03 08:39
Type 527 has those four dogma effects. Closing as by design.

**Closed by gitAskur** 2020-11-03 08:39 UTC
Labels: bug, esi-universe

**Comment by guiguilechat** [comment] 2020-11-03 11:03
and it misses the effect 586.
