### ISSUE TITLE
New characters: /v2/universe/names/ not consistent with /characters/{character_id}/

### ISSUE THREAD

**Issue by galister** [esi/esi-issues#1086] opened 2018-12-31 18:48 UTC
# Bug

The universe names endpoint will sometimes return an invalid ID error even after the characters endpoint verifies that the ID in question is valid and belongs to an alive character.

This becomes a pain if I need to pull a large amount of not-yet known characters that show up in someone's wallet journal, contacts or mail. I do not want to pull their whole character info, just the names, and even if one ID is not working, the whole request is botched.

I've observed this countless times and it seems that the ID usually **becomes available on the names endpoint after an hour or so.**

## Request & Response

The ID exists:
```
$ curl -X GET "https://esi.evetech.net/v4/characters/2114824579/?datasource=tranquility" -H "accept: application/json"
{
  "ancestry_id": 21,
  "birthday": "2018-12-31T17:59:19Z",
  "bloodline_id": 3,
  "corporation_id": 1000172,
  "description": "",
  "gender": "male",
  "name": "Nonious",
  "race_id": 2,
  "security_status": 0
}
```

But the names endpoint says otherwise:
```
$ curl -dX POST "https://esi.evetech.net/v2/universe/names/?datasource=tranquility" -H "accept: application/json" -H "Content-Type: application/json" -d "[ 2114824579]"
< HTTP/2 404
< date: Mon, 31 Dec 2018 18:30:08 GMT
< content-type: application/json; charset=UTF-8
< content-length: 54
< access-control-allow-credentials: true
< access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent
< access-control-allow-methods: POST,OPTIONS
< access-control-allow-origin: *
< access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
< access-control-max-age: 600
< allow: OPTIONS,POST
< strict-transport-security: max-age=31536000
< x-esi-error-limit-remain: 99
< x-esi-error-limit-reset: 52
< x-esi-request-id: 6a2e156e-a879-437d-bca2-a3a2649827b4

{"error":"Ensure all IDs are valid before resolving."}
```

## Expected

```
[{"category":"character","id":2114824579,"name":"Nonious"}]
```

I would expect this to not have such a delay for new characters, **or at the very least, not break the entire request** if 1 ID is bugged out of 150.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided
- [x] Happy new year

**Comment by ddavaham** [comment] 2018-12-31 20:09
I am unable to make a valid request with your curl statement, but the following is working for me. I copied yours and removed the -d at the beginning

`curl -X POST "https://esi.evetech.net/v2/universe/names/?datasource=tranquility" -H "accept: application/json" -H "Content-Type: application/json" -d "[ 2114824579]"`

```json
[{"category":"character","id":2114824579,"name":"Nonious"}]
```

**Comment by galister** [comment] 2019-01-01 02:31
Not being able to see a character right after it's been created I think is acceptable for such a versatile endpoint. The fact that it will fail an entire request which contains valid IDs that come from an endpoint such as wallet journal, is not.

Since the endpoint is not guaranteed to be able to provide up-to-date data, the requirements should be set accordingly. For example, allowing a limited number of misses, and returning the missed IDs along with the other valid results.

I would also like to say that the character affiliations endpoint does see characters right after creation, but since it does not return player names, we need to rely on universe names for batches of character IDs.

**Comment by ddavaham** [comment] 2019-01-01 03:58
It literally states in the description that all IDs must be valid else the request failed. The endpoint use be one that we could throw IDs at and it would return. Names for the valid ones, but it was abused and updated to only succeed if all the IDs submitted we're valid. Please reference the below blog detailing the change

https://developers.eveonline.com/blog/article/universe-names-update

I am closing this issue since the cause has been determined and resolution determined.

**Closed by ddavaham** 2019-01-01 03:58 UTC
Labels: bug, esi-universe

**Comment by Blacksmoke16** [comment] 2019-01-01 04:31
But the id is valid. If the characters endpoint can resolve it, this one should be able to as well IMO.
