### ISSUE TITLE
Add ENUM of allowed Flag IDs to POST /v1/characters/{character_id}/fittings/

### ISSUE THREAD

**Issue by ddavaham** [esi/esi-issues#1038] opened 2018-09-24 02:05 UTC
# Feature Request

When submitting a POST request to the /characters/{character_id}/fittings, if an invalid flag is provided for a fitting items flag property, the monolith error below is returned.

```
Failed HTTP Request POST /v1/characters/{character_id}/fittings/ : Http Status 520 || Error: {'error_label': 'InvalidFittingDataInvalidFlag', 'error_dict': {'type': 1952}}
```

Requesting an enum be added to the spec outlining which ids are acceptable for the flag property.

## Use Case

No Moar Monolith errors for invalid flag ids

## Authentication

Already in place on the endpoint

## Example Return

No needed in this case

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by Aidansavage** [comment] 2018-09-24 08:10
With fits, the only flags accepted iirc are module slots, drone/fighter bay, and cargo bay flags. Fleet Hangars and SMBs are not included.

:thinking: Would this be better as a feature request, rather than a bug report? The way I see it, to ESI, it's an acceptable flag, as it does exist elsewhere, but the monolith is rejecting it (hence 520s instead of 4xxs) because it's an invalid flag with respect to fits that are trying to be saved ingame.

**Comment by ddavaham** [comment] 2018-09-24 12:10
I have converted this to a feature request for an enum on the flag property of the fitting items array

**Comment by tsuthers-ccpgames** [comment] 2019-01-24 14:35
Sounds sensible, sadly will require a version bump but oh well.

**Comment by CarbonAlabel** [comment] 2019-01-24 14:40
Duplicate of #350 and #896.

**Comment by tsuthers-ccpgames** [comment] 2019-01-24 14:49
As per https://github.com/esi/esi-issues/issues/896 this also affects the GET route with the same path.

**Comment by tsuthers-ccpgames** [comment] 2019-01-24 16:31
Weird, there's code in here which definitely doesn't work on my local server.

**Comment by tsuthers-ccpgames** [comment] 2019-01-24 17:09
These are the valid flags: 
`[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 125, 126, 127, 128, 92, 93, 94, 164, 165, 166, 167, 168, 169, 170, 171]`

**Comment by ddavaham** [comment] 2019-01-24 17:22
Add 5 for the cargo hanger.

**Comment by tsuthers-ccpgames** [comment] 2019-01-25 17:11
I've got code checked in for this but I don't want to deploy it on friday evening, expect a dev release monday.

**Closed by tsuthers-ccpgames** 2019-01-25 17:11 UTC
Labels: esi-fittings, feature request

**Comment by tsuthers-ccpgames** [comment] 2019-01-28 16:09
Deployed.
