### ISSUE TITLE
Increase contract limit on /contracts/public/{region_id}/

### ISSUE THREAD

**Issue by StephenSwat** [esi/esi-issues#1028] opened 2018-09-04 21:22 UTC
# Feature Request

Let me preface this by saying that I'm completely aware of #1014. I'm also aware that the bug that existed before has been resolved and I'm aware that the devs have indicated that they plan to wait a few weeks to see the performance impact of this recently introduced endpoint. This is *not* a bug report and I'm not claiming that anything needs to be fixed or that anything needs to be done right now.

However, it is my opinion that the sanity limit on the public contract endpoint is still an issue and therefore I feel that it is appropriate to have an issue for it on the issue board. I'm submitting a feature request in the hope that it keeps the issue on the radar for when the ESI developers feel it is appropriate to revisit the sanity limit.

## Details

For the sake of being complete, this feature request concerns the `/contracts/public/{region_id}/` endpoint. The endpoint currently has a cap of 10,000 contracts returned per region. Since the endpoint appears to return 10,000 arbitrary contracts and some regions have more contracts than that, the usefulness of the public contract endpoint is currently severely limited. Indeed, The Forge is probably the biggest contract hub in the game and not being able to retrieve all contracts in that region makes some tools as useful as a chocolate teapot.

I request that, when the ESI developers feel it is appropriate to revisit this issue, the sanity limit either be increased or removed entirely. Should the developers be of the opinion that this is infeasible for whatever reason I would like to humbly request that they notify third party developers of their decision through any of many available channels.

**Comment by tsuthers-ccpgames** [comment] 2018-09-14 14:56
Mate, I said on the ticket that I would review after 2 weeks. Trust, yeah? 😄

If you /know/ that the issue is being looked at, opening redundant tickets increases the overhead of the esi-issues repo for us devs because we not only have to update the original ticket, but all the "Let me preface this by saying" tickets as well.

Closing redundant ticket, an update has been posted on https://github.com/esi/esi-issues/issues/1014 Please go there to view it.

**Closed by tsuthers-ccpgames** 2018-09-14 14:56 UTC
Labels: enhancement, esi-contracts
