### ISSUE TITLE
/search/?categories=solar_system with strict=true returns the system ID even if incorrect spelling

### ISSUE THREAD

**Issue by Gh0stReaper123** [esi/esi-issues#1294] opened 2021-08-31 17:00 UTC
# Bug

Despite setting the 'strict' parameter to 'true', entering 1DQ-1A (vs the real spelling 1DQ1-A) returns the system ID when it isn't a strict match

## Request

`GET latest/search/?categories=solar_system&datasource=tranquility&language=en&search=1DQ-1A&strict=true`

### Status Code

`200`

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json

{
  "solar_system": [
    30004759
  ]
}
```

## Expected

200
`{}`

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [ ] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by Dusty-Meg** [comment] 2021-08-31 20:21
See 
https://github.com/esi/esi-issues/issues/999#issuecomment-412536816

**Comment by Blacksmoke16** [comment] 2021-08-31 20:31
Duplicate of https://github.com/esi/esi-issues/issues/999

**Closed** 2021-08-31 20:31 UTC
Labels: bug, duplicate, esi-search
