### ISSUE TITLE
/corporations/{corporation_id}/wallets/{division}/transactions/ is returning 404

### ISSUE THREAD

**Issue by warlof** [esi/esi-issues#1183] opened 2020-03-19 07:28 UTC
# Bug

When requesting Corporation Wallet Transactions entries, I received a 404 Not Found

## Request

Be sure to include the HTTP method, path (including version), and any relevant parameters. Please do not include auth tokens. E.g.:

`GET curl -X GET /v1/corporations/98413060/wallets/2/transactions/?datasource=tranquility`

### Status Code

`404`

### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent
access-control-allow-methods: GET,HEAD,OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
access-control-max-age: 600
allow: GET,HEAD,OPTIONS
content-length: 21
content-type: application/json; charset=UTF-8
date: Thu, 19 Mar 2020 07:22:28 GMT
strict-transport-security: max-age=31536000
x-esi-error-limit-remain: 99
x-esi-error-limit-reset: 32
x-esi-request-id: 17cf8265-7612-4762-ba83-50ca5c1e7efc
x-firefox-spdy: h2
```

### Body

```json
{
  "error": "Not found"
}
```

## Expected

`200`

```
[
  {
    "client_id": 54321,
    "date": "2016-10-24T09:00:00Z",
    "is_buy": true,
    "journal_ref_id": 67890,
    "location_id": 60014719,
    "quantity": 1,
    "transaction_id": 1234567890,
    "type_id": 587,
    "unit_price": 1
  }
]
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by guiguilechat** [comment] 2020-03-19 08:22
duplicate of #1182 , should be fixed when CCP (re)start the faulty nodes.

**Comment by lukasni** [comment] 2020-03-19 16:15
This was a temporary issue that has been fixed as of about 2.5 hours ago

**Closed by lukasni** 2020-03-19 16:15 UTC
