### ISSUE TITLE
/universe/ids/ vs /universe/names/ use of category as attribute vs list name

### ISSUE THREAD

**Issue by DaneelTrevize** [esi/esi-issues#978] opened 2018-06-20 12:31 UTC
# Inconsistency

/universe/names/ returns a single list where every item must have a category string, from an enumeration.

/universe/ids/ returns several lists (technically objects because they're named?), where the category name is only transmitted once per list, rather than duplicated per item.  
This seems like it would be far more efficient in terms of data volume, as well as automatically sorting the results by category for easy use.

## Routes

- `POST /universe/ids/`
- `POST /universe/names/`

## Resolution

Remove the `category` attribute in the return of `POST /universe/names/`, instead divide the returned list by category as per the return of `POST /universe/ids/`.

# Checklist

Check all boxes that apply to this issue:

- [x] Inconsistency description is provided
- [x] Inconsistent route(s) are provided
- [x] Resolution [will require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)
- [ ] Resolution [does not require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)

**Comment by itshouldntdothis** [comment] 2018-06-20 12:36
dupe of #735.

**Closed by itshouldntdothis** 2018-06-20 12:36 UTC
