### ISSUE TITLE
Unhandled internal error on requesting items of a corp contract

### ISSUE THREAD

**Issue by Foiritain** [esi/esi-issues#795] opened 2018-03-15 14:21 UTC
# Bug
Trying to load items for contract #129893733 of corporation #1089040789 returns an Unhandled internal error. The contract is question is an outstanding courier contract from an NPC station to a citadel, created by another corp in my alliance to the alliance. 
### Request
/v1/corporations/1089040789/contracts/129893733/items/
### Response
{
  "error": "Unhandled internal error encountered!"
}
### Expected
Not that ^ 

An access denied message of some kind i guess as you cant see the items ingame.

**Comment by ccp-zoetrope** [comment] 2018-07-30 11:31
Duplicate of https://github.com/esi/esi-issues/issues/697.

**Closed by ccp-zoetrope** 2018-07-30 11:31 UTC
Labels: bug, esi-corporations
