### ISSUE TITLE
Clones endpoint home_location returns structure id as type "station"

### ISSUE THREAD

**Issue by irwiss** [esi/esi-issues#1184] opened 2020-03-20 23:30 UTC
# Bug

Getting several characters returning an id from structures range in clones endpoint

## Request

HTTP1.1 with and without etags

`https://esi.evetech.net/v3/characters/92062756/clones/`
`https://esi.evetech.net/v3/characters/2116294350/clones/`

## Response

For 92062756:
`{"home_location":{"location_id":10305647xxxxx,"location_type":"station"},"jump_clones":[]}`

![image](https://user-images.githubusercontent.com/6560075/77213040-0ffc5580-6b12-11ea-9193-4126be6b92fb.png)

For 2116294350:
![image](https://user-images.githubusercontent.com/6560075/77213966-78990180-6b15-11ea-97fb-0477a32beaeb.png)

### Status Code

`200` or `304` depending on etag

### Headers

For 92062756:

```
Date: 2020-03-20 23:22:54 +00:00
Expires: 2020-03-20 23:24:54 +00:00
X-ESI-Request-ID: 8d16789d-e668-4038-aa8c-dc99454be964
ETag: "f4f0a245d937132b00a780f0d5c99a5214c8d2c0a80c3853ec04bce7"
```

Another request:
X-Esi-Request-Id: `a763be5a-facf-41e7-994e-2dc7f9aa878d`
Date: `Fri, 20 Mar 2020 23:22:54 GMT`
ETag: `"f4f0a245d937132b00a780f0d5c99a5214c8d2c0a80c3853ec04bce7"`

For 2116294350:
Date: `Fri, 20 Mar 2020 23:37:25 GMT`
X-Esi-Request-Id: `aa757dc6-cfa4-410e-bf1b-d1414e5d1313`
ETag: `"2e49f7fb4ce7a29c3949171c5a980d90440f73d83ea1a8bf0ea766cb"`

### Body

For 92062756:
```json
{"home_location":{"location_id":10305647xxxxx,"location_type":"station"},"jump_clones":[]}
```

For 2116294350:

```json
{"home_location":{"location_id":10294813xxxxx,"location_type":"station"},"jump_clones":[],"last_station_change_date":"2020-02-08T10:00:14Z"}
```

## Expected

`200` or `304` but either valid station id or not `station` in `location_type`

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by lukasni** [comment] 2020-03-21 00:48
After some testing with ~350 characters I'm not seeing _any_ correct results. I have 22 characters with a `home_location` `location_id` that appears to be a tructure, all of which are incorrectly returning a `location_type` of `station`

**Comment by irwiss** [comment] 2020-03-21 12:22
Also probably related, request:
X-Esi-Request-Id: `84e7d062-30a8-4bea-a6a1-08136a08ff7f`
Date: `Sat, 21 Mar 2020 12:17:06 GMT`
ETag: `"c43eb93363c24e89146c32849cf3c152ba552511c815def9aaa93cdd"`

Response: ```{"home_location":{"location_id":1031xxxxxxxxx,"location_type":"station"},"jump_clones":[{"implants":[],"jump_clone_id":55612153,"location_id":60003466,"location_type":"station"},{"implants":[],"jump_clone_id":57317915,"location_id":60004525,"location_type":"station"},{"implants":[],"jump_clone_id":56043367,"location_id":60008494,"location_type":"station"},{"implants":[10228,13217,13244,13253,13262,22107,22108,22109,22110,22111],"jump_clone_id":57358913,"location_id":0,"location_type":"station"},{"implants":[],"jump_clone_id":57343512,"location_id":0,"location_type":"station"}],"last_clone_jump_date":"2020-03-19T12:51:48Z","last_station_change_date":"2018-01-06T19:45:32Z"}```

Note the `"location_id": 0` for one of the jump clones

**Comment by irwiss** [comment] 2020-03-23 13:48
Stopped getting these after 23 Mar 2020 09:40:43.000 which seems to correlate with when esi started barfing and subsequent restart.

Feel free to close if no one experiences this anymore

**Comment by lukasni** [comment] 2020-03-23 20:09
Confirmed, seeing the same on my end. I'll close it.

**Comment by rangvaldr** [comment] 2020-07-16 13:26
This has been happening to me as recent as today. All ESI clones requests are returning the location types as "station", even if they aren't.

**Comment by rangvaldr** [comment] 2020-08-01 17:22
@mateuszkrasucki Sorry for the delay, looks like it's working.

**Closed** 2020-08-01 18:42 UTC
Labels: bug, esi-clones
