### ISSUE TITLE
Add structure_id to the response of /universe/structures/{structure_id}/

### ISSUE THREAD

**Issue by ebeisecker** [esi/esi-issues#1343] opened 2023-01-23 13:50 UTC
# Feature Request

It would be nice if the response from `/universe/structures/{structure_id}/` would return the ID of the structure being queries `structure_id`. 

## Use case

When writing an application that deserializes the response of `/universe/structures/{structure_id}/` into an object it's messy to have to manually "add" the `structure_id` to object instead of it being populated as part of the deserialization process

## Authentication

This would be modifying the existing route that uses scope `esi-universe.read_structures.v1`

## Example return

Propose what an example return might look like. E.g.:

`GET /universe/structures/123456789/?datasource=tranquility`
```json
{
  "name": "My Structure",
  "owner_id": 1234567,
  "position": {
    "x": -112983717892,
    "y": 123897598718,
    "z": 105182759178
  },
  "solar_system_id": 3456768,
  "type_id": 345678,
  "structure_id": 123456789
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [ ] Feature requires a new route
- [x] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by Blacksmoke16** [comment] 2023-01-23 14:05
Duplicate of #1122

**Closed by Blacksmoke16** 2023-01-23 14:05 UTC
Labels: duplicate, esi-universe, inconsistency
