### ISSUE TITLE
ESI /route/ endpoint returns invalid routes after Pochven separation

### ISSUE THREAD

**Issue by tcstudios** [esi/esi-issues#1251] opened 2020-10-30 12:51 UTC
# Bug

When using ESI to get a route between two systems that would previously have gone through one of the Trig captured systems, it returns an invalid route.

Example: Madrimilire -> Jita
Route returned: Madrimilire -> *** Niarja *** -> Kaaputenen -> .... -> Jita

## Request

 GET /route/30003503/30000142/?datasource=tranquility&flag=shortest

## Response

[
  30003503,
  30003504,    <<- this jump doesn't exist
  30002789,
  30002788,
  30002791,
  30000139,
  30000144,
  30000142
]

### Status Code

200

### Headers

None Relevant

### Body

See Above

## Expected

This is the same request, but with 30003504 (Niarja) in the avoidance list

[
  30003503,
  30004080,
  30004079,
  30004078,
  30004083,
  30005192,
  30005193,
  30005194,
  30005195,
  30005205,
  30005200,
  30005199,
  30005198,
  30005015,
  30002761,
  30002764,
  30002765,
  30002768,
  30002803,
  30002805,
  30002791,
  30000139,
  30000144,
  30000142
]

# Checklist

Check all boxes that apply to this issue:

- [ x] Bug description is provided
- [ x] Request path is provided
- [ x] Response status code is provided
- [ ] Response headers are provided
- [ x] Response body is provided
- [ x] Expected response is provided

**Comment by Blacksmoke16** [comment] 2020-10-30 13:19
Duplicate of https://github.com/esi/esi-routes/issues/7.

**Closed by Blacksmoke16** 2020-10-30 13:19 UTC
Labels: bug, duplicate, esi-routes

**Comment by guiguilechat** [comment] 2020-10-31 14:45
@tcstudios  temporary workaround : list the systems in the pochven region and add the 27 to the avoidance list when making your call.
