### ISSUE TITLE
Incomplete responses from /universe/ids/

### ISSUE THREAD

**Issue by colcrunch** [esi/esi-issues#1228] opened 2020-08-16 08:47 UTC
# Bug

Requests to `/universe/ids/` is returning incomplete responses for various strings (mainly inventory types).

## Request

Example curl request: 
    `curl -X POST "https://esi.evetech.net/latest/universe/ids/?datasource=tranquility&language=en-us" -H "accept: application/json" -H "Accept-Language: en-us" -H "Content-Type: application/json" -d "[ \"Loki\"]"`

### Status Code

`200`

### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```
 access-control-allow-credentials: true 
 access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent 
 access-control-allow-methods: POST,OPTIONS 
 access-control-allow-origin: * 
 access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset 
 access-control-max-age: 600 
 allow: OPTIONS,POST 
 content-language: en-us 
 content-length: 100 
 content-type: application/json; charset=UTF-8 
 date: Sun, 16 Aug 2020 08:37:23 GMT 
 status: 200 
 strict-transport-security: max-age=31536000 
 vary: Accept-Language 
 x-esi-error-limit-remain: 100 
 x-esi-error-limit-reset: 37 
 x-esi-request-id: 568801c8-1250-490c-8ea4-9e2facd20506 
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{
  "characters": [
    {
      "id": 144552144,
      "name": "Loki"
    }
  ],
  "corporations": [
    {
      "id": 189191279,
      "name": "LOKI inc."
    }
  ]
}
```

## Expected

In the provided example, the response should also include an `inventory_types` section with the Loki's type id.

# Checklist

Check all boxes that apply to this issue:

- [ ] Bug description is provided
- [ ] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by lukasni** [comment] 2020-08-17 19:00
@gitAskur This may be related to #1181, specifically mixing "items" and "types", that is static types like a ship type and dynamic items like characters and corporations.

**Comment by gitAskur** [comment] 2020-08-18 09:22
```
λ curl -X POST "https://esi.evetech.net/latest/universe/ids/?datasource=tranquility&language=en-us" -H "accept: application/json" -H "Accept-Language: en-us" -H "Content-Type: application/json" -d "[ \"Loki\"]"
```

Returns

```
{"characters":[{"id":144552144,"name":"Loki"}],"corporations":[{"id":189191279,"name":"LOKI inc."}],"inventory_types":[{"id":29990,"name":"Loki"}]}
```

Which includes the inventory types. Tried this for `Retribution` and `Coercer` as well and got a character and inventory type in both cases.

That being said this endpoint is terrible as it has no context and we should not be offering endpoints like this. It may be flakey but unless there is a solid repro case for missing but expected currently supported functionality I need to direct my focus elsewhere.

**Comment by glelouet** [comment] 2020-08-18 09:54
@gitAskur  you closed the issue.

I think adding a wont fix tag instead is the correct move. The issue is not fixed, but so low on the priority list that we can assume it won't be fixed and the "fix" will be the removal when the ESI is redesigned.

**Comment by gitAskur** [comment] 2020-08-18 10:16
I couldn't reproduce it, so I didn't tag at as "Wont Fix" as that would imply I could have reproduced it and decided to leave it broken. If this is steadily reproducable for you please give me repro steps :)

**Comment by glelouet** [comment] 2020-08-18 10:19
Sorry then, you're right.

**Comment by pvyParts** [comment] 2020-08-19 02:31
I have the issue in my Dev enviro, it also happens on the esi web UI.

### reproduction
https://esi.evetech.net/ui#/Universe/post_universe_ids
#### Paramaters
```ids=["Curse", "Sabre"]```

### Result
```
{
   "characters":[
      {
         "id":144518812,
         "name":"Sabre"
      }
   ],
   "corporations":[
      {
         "id":699530819,
         "name":"The Accursed"
      },
      {
         "id":645904291,
         "name":"Saber Inc"
      }
   ],
   "inventory_types":[
      {
         "id":22456,
         "name":"Sabre"
      }
   ]
}```

x-esi-request-id: 5edffd76-65aa-4623-9049-a15a96cb1466

### expected
```{
...
   "inventory_types":[
      {
         "id":22456,
         "name":"Sabre"
      },
      {
         "id":20125,
         "name":"Curse"
      }
   ]
"

**Comment by gitAskur** [comment] 2020-08-19 08:00
```
λ curl -X POST "https://esi.evetech.net/latest/universe/ids/?datasource=tranquility&language=en-us" -H "accept: application/json" -H "Accept-Language: en-us" -H "Content-Type: application/json" -d "[ \"Curse\"]"

{"corporations":[{"id":699530819,"name":"The Accursed"}]}
```

Curse still exists as typeID 20125.

**Comment by CarbonAlabel** [comment] 2020-08-19 08:13
> Curse still exists as typeID 20125.

Also as a region.

**Comment by jamesrobb** [comment] 2020-11-12 11:30
We believe this issue to be fixed on our end. @colcrunch can you verify you are getting the expected response?

**Comment by pvyParts** [comment] 2020-11-12 12:26
I checked the ones I know we're not working last time looking good now!

`names= ["Curse", "Sabre"]`

```json
{
  "alliances": [
    {
      "id": 99005809,
      "name": "Cursed Legion."
    }
  ],
  "characters": [
    {
      "id": 144518812,
      "name": "Sabre"
    }
  ],
  "corporations": [
    {
      "id": 699530819,
      "name": "The Accursed"
    },
    {
      "id": 645904291,
      "name": "Saber Inc"
    }
  ],
  "inventory_types": [
    {
      "id": 20125,
      "name": "Curse"
    },
    {
      "id": 22456,
      "name": "Sabre"
    }
  ],
  "regions": [
    {
      "id": 10000012,
      "name": "Curse"
    }
  ]
}```

**Comment by jamesrobb** [comment] 2020-11-12 12:50
Great! I'm going to close this issue, then. Please do feel-free to open it again if something is amiss.

**Closed by jamesrobb** 2020-11-12 12:50 UTC
Labels: Internal Issue Created, bug, esi-search

**Comment by acreter** [comment] 2022-04-13 08:38
I noticed that the endpoint does not return the intentory_types result for most of the recently added 'Compressed' ores, e.g. 'Compressed Pyroxeres'

`curl -X POST "https://esi.evetech.net/latest/universe/ids/?datasource=tranquility&language=en-us" -H "accept: application/json" -H "Accept-Language: en-us" -H "Content-Type: application/json" -d "[\"Compressed Pyroxeres\"]"`

returns

`{}`

**Comment by LeoJian622** [comment] 2022-04-13 08:38
收到勒。。。(-o-)／   _(_^_)_  请不要介意这封自动回复。。。。

**Comment by GoldenGnu** [comment] 2022-04-13 08:53
@acreter
`Compressed Pyroxeres ` (Note the space at the end) works. The trailing space is in the SDE too.
So, that is somehow the official name, I know it have been reported already, so, hopefully it will be resolved soon.

**Comment by acreter** [comment] 2022-04-13 09:06
@GoldenGnu 
That indeed solved the issue, thank you very much.
