### ISSUE TITLE
Rename alliance_id in race API to faction_id

### ISSUE THREAD

**Issue by biow0lf** [esi/esi-issues#1211] opened 2020-06-03 18:30 UTC
# Bug

Endpoint `/v1/universe/races/` returns JSON (output reduced to show only first race):

```json
[
  {
    "alliance_id": 500001,
    "description": "Founded...",
    "name": "Caldari",
    "race_id": 1
  }
]
```

But Alliance with ID 500001 don't exists. Because this is faction.

**Comment by Blacksmoke16** [comment] 2020-06-03 18:37
Duplicate of https://github.com/esi/esi-issues/issues/812.

**Closed by Blacksmoke16** 2020-06-03 18:37 UTC
