### ISSUE TITLE
Ship Names no longer return in proper format

### ISSUE THREAD

**Issue by w9jds** [esi/esi-issues#1194] opened 2020-04-16 23:56 UTC
# Bug

Ship names are no longer returns in an escaped string format

## Request

`GET /characters/{character_id}/ship/`

## Response

 `u'\xab\u263c\xbb \u2665Drogon\u2665'`

### Status Code

`200`

## Expected

The old way, before you tried to remove unicode ship names, was an escaped string of the ship name. That is no longer how it is returned...

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [ ] Request path is provided
- [ ] Response status code is provided
- [ ] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by exodus4d** [comment] 2020-04-18 23:07
I can confirm this issue. 
There are more issues with UTF-16 deconding background appearing in my log files:

e.g.  If there are special UTF-16 characters in corporation description, the response can not be decoded by using PHPs native[`.json-decode()`](https://www.php.net/manual/de/function.json-decode.php)
Error: 
> _json_decode() error: Single unpaired UTF-16 surrogate in unicode escape_

https://user-images.githubusercontent.com/59426933/79076900-55541300-7ccb-11ea-9b92-d39eee1945eb.PNG
See: https://github.com/exodus4d/pathfinder/issues/948#issue-598573009

**Comment by biow0lf** [comment] 2020-04-19 16:48
Looks like fixed. Can anyone confirm?

**Comment by w9jds** [comment] 2020-04-24 19:42
No, this isn't entirely fixed. I see some of them are returning correctly, but I'm still seeing some formatted like originally reported and even some with double quotes now.

**Comment by burberius** [comment] 2020-05-01 20:48
I have the same problem, looks to me like there are some of the endpoint nodes fixed, some broken.

`
[INFO ] 2020-05-01 18:56:42.233 [http-nio-127.0.0.1-8080-exec-6] LocationService - Shipname Würmchen with locale en`
`
[INFO ] 2020-05-01 19:55:21.709 [http-nio-127.0.0.1-8080-exec-2] LocationService - Shipname u'W\xfcrmchen' with locale en
`

I hope that gets fixed soon!

**Comment by gitAskur** [comment] 2020-11-03 08:58
I believe this has been properly fixed now. Please feel free to reopen if there are still instances of this and I will recreate the internal issue with new info.

**Closed by gitAskur** 2020-11-03 08:58 UTC
Labels: bug, esi-characters
