### ISSUE TITLE
[inconsistency] corporation/${id}/mining paths shoud be corporations/${id}/mining (with an 's' )

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#1098] opened 2019-03-03 14:18 UTC
# Inconsistency

three routes only use the corporation/ path. Other routes linked to corporation use the corporations/ path.

## Routes

 - https://esi.evetech.net/v1/corporation/{corporation_id}/mining/extractions/
 - https://esi.evetech.net/v1/corporation/{corporation_id}/mining/observers/
 - https://esi.evetech.net/v1/corporation/{corporation_id}/mining/observers/{observer_id}/

## Resolution

sed s+corporation/+corporations/+g

# Checklist

Check all boxes that apply to this issue:

- [x] Inconsistency description is provided
- [x] Inconsistent route(s) are provided
- [x] Resolution [will require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)
- [ ] Resolution [does not require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)

**Comment by jowrjowr** [comment] 2019-03-03 14:40
this is literally not worth anyone's time to fix.

**Comment by Blacksmoke16** [comment] 2019-03-03 14:41
Duplicate of https://github.com/esi/esi-issues/issues/623

**Closed by jowrjowr** 2019-03-03 14:40 UTC
Labels: esi-industry, inconsistency

**Comment by guiguilechat** [comment] 2019-03-03 14:49
even it's it not gonna be fixed it is still an inconsistency. Add it the "won't fix" tag.
