### ISSUE TITLE
'Perimeter - Tranquility Trading Tower' Sell orders missing

### ISSUE THREAD

**Issue by MANABbl4** [esi/esi-issues#1202] opened 2020-05-08 17:15 UTC
# Inconsistency

Endpoint '/markets/{region_id}/orders/' doesn't return sell orders from structure 'Perimeter - Tranquility Trading Tower', but buy orders works fine.

Also this endpoint sometime return some orders with location_id's (1028370750672, 1022179194562) which cannot be resolved with '/universe/structures/{structure_id}/' endpoint and it returns error "Forbidden"

## Routes
- `GET /markets/{region_id}/orders/`
- `/universe/structures/{structure_id}/`

## Resolution

- Return both buy and sell orders for the endpoint or doesn't return them at all and say 'use /markets/structures/{structure_id}/ endpoint'.
- Doesn't return market orders with invalid location_id's or allow to resolve it

# Checklist

Check all boxes that apply to this issue:

- [x] Inconsistency description is provided
- [x] Inconsistent route(s) are provided
- [ ] Resolution [will require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)
- [x] Resolution [does not require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)

**Comment by Blacksmoke16** [comment] 2020-05-08 17:32
This is an explicit design choice and isn't going to change.  See https://github.com/esi/esi-issues/issues/826#issuecomment-384686625

Duplicate of #826

**Closed by Blacksmoke16** 2020-05-08 17:32 UTC
Labels: duplicate, esi-markets

**Comment by lukasni** [comment] 2020-05-08 18:31
Regarding the "invalid" `location_id`s, those aren't invalid IDs, they are structures that your resolving characters doesn't have docking access to. This, also, is a design choice, and the reason why the market order result also includes the `system_id`, that way you still know which system the order is in even if you don't have access to resolve the structure.

**Comment by MANABbl4** [comment] 2020-05-09 07:32
@lukasni Thank you!
