### ISSUE TITLE
[duplicate] contract items shows no value for a BPO's runs, doc says -1

### ISSUE THREAD

**Issue by guiguilechat** [esi/esi-issues#1403] opened 2024-12-19 16:43 UTC
duplicate of #827 #1241 

This path https://esi.evetech.net/ui/#/Contracts/get_contracts_public_items_contract_id

specifies 

runs
 integer($int32)
 minimum: -1
 title: get_contracts_public_items_contract_id_runs
 Number of runs remaining if the blueprint is a copy, -1 if it is an original

This contract offers only one BPO 10/20 : 

![image](https://github.com/user-attachments/assets/07778051-d452-447f-af3f-8eb345a2f9e2)

however fetching its list of items with https://esi.evetech.net/latest/contracts/public/items/212609552/?datasource=tranquility&page=1

returns 

```
[
  {
    "is_included": true,
    "item_id": 1047439047963,
    "material_efficiency": 10,
    "quantity": 1,
    "record_id": 4632163434,
    "time_efficiency": 20,
    "type_id": 17357
  }
]
```

in which the "runs" field is not present.

fix : update the documentation (easiest), update the return to have -1 for bpos stacks and singletons, absent for non-BP, runs for BPCs.

**Comment by Dusty-Meg** [comment] 2024-12-24 07:17
Duplicate of #1241

**Comment by Dusty-Meg** [comment] 2024-12-24 07:19
Which both are kind of redundant for #827

**Comment by guiguilechat** [comment] 2024-12-24 09:12
@Dusty-Meg  thx, closed.

**Closed** 2024-12-24 09:12 UTC
