### ISSUE TITLE
Feature Request : Write to Corp/Alliance calendar

### ISSUE THREAD

**Issue by Nuramori** [esi/esi-issues#1106] opened 2019-04-02 23:05 UTC
Currently entries in the corporation/alliance level calendar entries can be read, but none can be created nor edited.  The ability to write entries based on communications roles would assist in app development tailored to conditional events.

**Comment by Blacksmoke16** [comment] 2019-04-02 23:11
Duplicate of https://github.com/esi/esi-issues/issues/164

**Closed by Blacksmoke16** 2019-04-02 23:11 UTC
Labels: duplicate, esi-calendar
