### ISSUE TITLE
Feature Request /fleets/{fleet_id}/members/ add docked state or show citadels instead of stations only

### ISSUE THREAD

**Issue by tict4c** [esi/esi-issues#1126] opened 2019-07-06 15:07 UTC
# Feature Request
Currently it is only possible to check if a fleet member is docked if the member is inside of astation citadels will not return a ID. 

Sugested change is to also provide an ID if the fleet member is docked in citadels. 

In case of game designe concerns alternative adding a "is_docked" flag would help with my use case as well

## Use case

Benefits Fleetcomanders since they can be shown who is docked in their fleet and which player is actually active with the fc.

## Authentication

Same as now

## Example return

Propose what an example return might look like. E.g.:

```json
[
  {
    current returns,
   "is_docked": true
  },

]
```

# Checklist

- [x ] Feature request description is provided
- [x ] Use case exists
- [ ] Feature requires a new route
- [x ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [ x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by Blacksmoke16** [comment] 2019-07-06 15:13
Duplicate of https://github.com/esi/esi-issues/issues/427

**Closed by Blacksmoke16** 2019-07-06 15:13 UTC
