### ISSUE TITLE
Endpoint sometimes returns text/html instead of json when giving 504 error

### ISSUE THREAD

**Issue by mcgibbon** [esi/esi-issues#1102] opened 2019-03-24 03:11 UTC
# Bug

When contacting the `markets/{region_id}/orders/` endpoint, the endpoint sometimes gives return data of type `text/html`, with a title, head, and everything, instead of json as expected. This leads to a crash in `pyswagger` which I am using to call the endpoint. This just started happening recently. I still also get 504 errors which correctly return something like `{'error': 'description'}` and are processed properly by `pyswagger` (it retries the call).

Note I am not complaining that there's a 504! The endpoint is supposed to return its body as json when it 504's (and I believe did until recently, my code hasn't changed since I started getting this crash).

## Request

`GET /latest/markets/{region_id}/orders/?type_id={type_id}&order_type=buy`

## Response

`b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n'`

### Status Code

`504`

### Headers

Unknown, sorry. These aren't printed by the stack trace I get from pyswagger.

### Body

See Response, above.

## Expected

A return status of `504` with something like `{'error': 'gateway time-out'}` as the json body of the response.

# Checklist

Check all boxes that apply to this issue:

- [X] Bug description is provided
- [X] Request path is provided
- [X] Response status code is provided
- [Nope] Response headers are provided
- [X] Response body is provided
- [X] Expected response is provided

If you absolutely need the headers, let me know and I can see how I might hack pyswagger's code to output them. You can find the stack trace I'm getting [here](https://github.com/Kyria/EsiPy/issues/49).

**Comment by CarbonAlabel** [comment] 2019-03-24 03:29
This is happening due to the request failing before reaching ESI proper. Not much can be done except modifying your code to handle such cases.

Duplicate of #953.

**Closed by CarbonAlabel** 2019-03-24 03:29 UTC
