### ISSUE TITLE
ACL profile

### ISSUE THREAD

**Issue by winterwings** [esi/esi-issues#1158] opened 2019-12-02 18:35 UTC
# Feature Request

An endpoint to view ACL profile or list all of the available profiles.

`/corporations/{corporation_id}/acl/{profile_id}` maybe?
Or a list of ACL profiles, similar to the list of corporate structures.

## Use case

I'm developing a tool that has a calendar with fuel expiration dates. Currently, access to this information is limited to pilots with Starbase Manager in-game role, but ACL allows to manage fuel out of a corporation. I want to handle this since it's a requested feature in my coalition.

`/corporations/{corporation_id}/structures/` teases with `profile_id` of ACL profile, but there's no way to view that profile. I believe it is a forgotten feature.

## Authentication

Likely the same `esi-corporations.read_structures.v1` since they are closely related.

(And it will be a pain to force all directors to update their auth with a new scope.)

## Example return

Details for that profile :)

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [x] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by Dusty-Meg** [comment] 2019-12-02 18:37
Duplicate of #55

**Closed** 2019-12-02 18:42 UTC
Labels: duplicate, esi-acls, feature request
