### ISSUE TITLE
Endpoint vs. in-game market history data

### ISSUE THREAD

**Issue by FabianPiconeDev** [esi/esi-issues#1112] opened 2019-04-11 17:16 UTC
# Inconsistency

As i understand, the price history in-game (market window -> product -> price history table) should be the same as the `/markets/{region_id}/history` data. But they are inconsistent to each other.

Example: I fetch the price history of product id 20869 (True Sanshas Infrared M) in region id 10000032 (Sing Laison). The in-game data shows me history entries for an entire year starting from now, with 0 orders/0 quantity on each entry. When i fetch that over the endpoint, i receive only 8 history entries from year 2018.

Anything wrong with the queries or dumps, or did i misunderstood something?

## Routes

- `GET /markets/{region_id}/history/`

## Resolution

The in-game data should be the same as the fetched data over the endpoint.

# Checklist

- [x] Inconsistency description is provided
- [x] Inconsistent route(s) are provided
- [ ] Resolution [will require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)
- [x] Resolution [does not require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)

**Comment by guiguilechat** [comment] 2019-04-11 17:37
duplicate of  #1111 ?

**Comment by FabianPiconeDev** [comment] 2019-04-11 18:28
> duplicate of #1111 ?

Indeed as you report, after i inspected the year-entries in-game searching for the returned data from the endpoint, these were the only entries with reported orders. So the days without sales are not returned in the endpoint response.

But there is still the inconsistency of the zeropadding. How about to simply strip off the padding in-game? Why should the padding be good for? As @tsuthers-ccpgames [says](https://github.com/esi/esi-issues/issues/1111#issuecomment-481694443) it could also save resources.

**Comment by Blacksmoke16** [comment] 2021-05-20 00:25
Duplicate of #1111

**Closed by Blacksmoke16** 2021-05-20 00:25 UTC
Labels: duplicate, esi-markets, feature request
