### ISSUE TITLE
When posting two items that differ only in case to /universe/id results in an ISE

### ISSUE THREAD

**Issue by Lucius-Q-User** [esi/esi-issues#1147] opened 2019-09-19 08:31 UTC
# Bug
When posting two items that differ only in case to /universe/ids (i.e. ["CCP Zoetrope", "ccp zoetrope"]) the server responds with 500.

## Request

`curl -X POST "https://esi.evetech.net/latest/universe/ids/?datasource=tranquility&language=en-us" -H  "accept: application/json" -H  "Accept-Language: en-us" -H  "Content-Type: application/json" -d "[\"CCP Zoetrope\", \"ccp zoetrope\"]"`

### Status Code

`500`

### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent  access-control-allow-methods: POST,OPTIONS  
access-control-allow-origin: *  
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset  
access-control-max-age: 600  
allow: OPTIONS,POST  
content-length: 125  
content-type: application/json; charset=UTF-8 
date: Thu, 19 Sep 2019 08:28:01 GMT
strict-transport-security: max-age=31536000
x-esi-error-limit-remain: 99 
x-esi-error-limit-reset: 59 
x-esi-request-id: 3b6650ec-71eb-4a29-a2b8-29d237af0c60 
x-firefox-spdy: h2 
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```json
{
  "error": "Internal error",
  "request_id": "3b6650ec-71eb-4a29-a2b8-29d237af0c60",
  "sentry_id": "4275864a7928402cba0575cd22566d57"
}
```

## Expected

`400`
```json
{
  "error": "'names' items are not all unique, 'names' is required"
}
```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by gitAskur** [comment] 2020-11-30 10:17
Closing as ´cannot reproduce´

λ curl -X POST "https://esi.evetech.net/latest/universe/ids/?datasource=tranquility&language=en-us" -H "accept: application/json" -H "Accept-Language: en-us" -H "Content-Type: application/json" -d "[ \"CCP Zoetrope\", \"ccp zoetrope\"]"
{"characters":[{"id":2112625428,"name":"CCP Zoetrope"}]}

**Closed by gitAskur** 2020-11-30 10:17 UTC
Labels: bug, esi-universe
