### ISSUE TITLE
Missing multiple columns in various contract item endpoints

### ISSUE THREAD

**Issue by NicolasKion** [esi/esi-issues#1396] opened 2024-10-28 14:22 UTC
# Inconsistency

The public contract item endpoint returns the following columns which are not present on other endpoints:

- item_id
- is_blueprint_copy
- time_efficiency
- material_efficiency
- runs

## Routes

Missing item_id, is_blueprint_copy, time_efficiency, material_efficiency and runs:

- `GET /v1/characters/{character_id}/contracts/{contract_id}/items/`
- `GET /corporations/{corporation_id}/contracts/{contract_id}/items/`

## Resolution

Add the missing columns to the other endpoints, which will result in them being far more useful for 3rd party services that deal with unique items, like abyssal modules or AT ships. Since this is a pure enhancement no breaking change is needed and it will not affect existing applications.

# Checklist

Check all boxes that apply to this issue:

- [x] Inconsistency description is provided
- [x] Inconsistent route(s) are provided
- [ ] Resolution [will require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)
- [x] Resolution [does not require a version bump](https://docs.esi.evetech.net/docs/breaking_changes)

**Comment by Dusty-Meg** [comment] 2024-10-29 07:02
Duplicate of #827 and #951

**Closed** 2024-10-29 12:51 UTC
Labels: bug, duplicate, esi-contracts
