### ISSUE TITLE
Corp Blueprint Endpoint Limited to 25 pages

### ISSUE THREAD

**Issue by adgriff2** [esi/esi-issues#1083] opened 2018-12-21 19:36 UTC
# Bug

Corporation has more than 25k blueprints unlocked. Corp blueprints endpoint x-pages header shows 25 pages and we get exactly 25k prints back. 

## Request
GET /corporations/{corporation_id}/blueprints/

### Status Code

200

### Headers

X-Pages: 25

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [ ] Response body is provided
- [ ] Expected response is provided

**Comment by tsuthers-ccpgames** [comment] 2018-12-21 20:40
I'll have to check when I get back in the office, which won't be until early Jan, but I'm pretty sure given how round and human-sounding that number is that this will turn out to be caused by a sanity limit in the DB proc to protect the DB from dangerously long running queries.

If that's the case, I won't be raising that limit. Corporations in this situation might want to consider subdividing their assets to multiple corps and possibly forming an alliance anyway, that'll lower the risk of a catastrophic smash-and-grab.

**Comment by adgriff2** [comment] 2018-12-21 20:44
It may be helpful to add a flag to return either only BPCs or BPOs to reduce the load of either query.

**Comment by excoecariaagallocha** [comment] 2018-12-30 15:16
Limiting by structure and hangars is a really good idea, likewise flagging for BPC/BPO types, or even an activity type ( show me all the blueprints that can be copied, or show all that are for reactions ) would be very straightforward ways of reducing the result set.

Blueprints can be locked to prevent theft, though the blueprint locking/unlocking mechanism needs work to be more user-friendly.  The ability to hard-lock a blueprint in a container via a vote, or the container itself ( and implicitly its contents ) would make things much more manageable.

Splitting up blueprints between corporations is a pain if you have industrialists who need access to the whole portfolio, it also means that to run corporation level jobs, you're now having to transfer not just blueprints, but their inputs and potentially outputs too.

More places to put things also means an increased chance of something being in the wrong place, ie, if all the mexalon ends up in one corporate hangar, the other corporations won't be able to do builds requiring it.  If inputs could be placed in an alliance-level hangar this would be mitigated, though its not an ideal system depending on what alliance you are in.

**Comment by jbs1** [comment] 2019-06-04 21:17
as per Diana Olympos advice i would like to ask if has been confirmed whether it was a DB sanity limit or not.
Also i would like to add the consideration, that the assets endpoint does not seem to have this limit when it can have much longer queries while this endpoint has.

**Comment by adgriff2** [comment] 2019-06-05 13:45
I believe the BP endpoint has this more restrictive limit because it shares some resource upstream that is also used by the in-game industry window. The search behavior of the industry window changes with regard to dropdown boxes (not just speed) exactly when you exceed this limit.

**Comment by jbs1** [comment] 2019-06-11 19:03
So ingame I can limit the searchspace, right? Which means ingame the limit is not so much a problem.
Assuming a corp as a like 50.000 bpc's ingame in one station with like 4 hangars containing 12,5 k each only the first 25 k will show up if you show "All Inventory Locations", right?
However you can still limits the search to each hangar separately then all BPC's would show up if you would go through each container separately? Or is this not the case?

If that is the case, the 25 k limit is not a big problem ingame at all, more like a minor annoyance.

But since the endpoint can't do any filtering if will just randomly not show some bpc's, which makes this endpoint next to useless for anything more than a minor industry operation on corp level.
Or am i missing something here?

**Comment by BlubQ** [comment] 2019-06-12 01:35
> However you can still limits the search to each hangar separately then all BPC's would show up if you would go through each container separately? Or is this not the case?

Nope, doesnt work like that.
It pulls the first 25k blueprints it can find and applies filter settings after that.
I've been on a crusade for years to somehow convince CCP that it cant stay like this but so far I had no luck.

**Comment by jbs1** [comment] 2019-06-19 06:04
are sure about that? Because I was able the see the newly added BP's in the ingame industry window that i could not see on the endpoint?

**Comment by tsuthers-ccpgames** [comment] 2019-06-19 11:00
Yeah, so this is indeed a sanity limit on the proc. I've spoken to people about this in depth now. Lifting blueprints out of the DB is extremely heavy because we have to recurse potentially up to like 6 layers deep or something to find them. I appreciate that this is a pain point, but I'm going to close this ticket because short of a total rewrite of the blueprints system this limit is not going to be changing either in the API or in game.

**Closed by tsuthers-ccpgames** 2019-06-19 11:00 UTC
Labels: bug, esi-corporations
