### ISSUE TITLE
Fetching character market orders returns 404

### ISSUE THREAD

**Issue by PhenomPBG** [esi/esi-issues#1262] opened 2020-12-04 06:47 UTC
# Bug

 When fetching character market orders I receive a 404 using the python swagger_client.

## Request

  File "C:\dev\eve_theurgy\swagger_client\api\market_api.py", line 58, in get_characters_character_id_orders
    (data) = self.get_characters_character_id_orders_with_http_info(character_id, **kwargs)  # noqa: E501
  File "C:\dev\eve_theurgy\swagger_client\api\market_api.py", line 133, in get_characters_character_id_orders_with_http_info
    return self.api_client.call_api(
  File "C:\dev\eve_theurgy\swagger_client\api_client.py", line 325, in call_api
    return self.__call_api(resource_path, method,
  File "C:\dev\eve_theurgy\swagger_client\api_client.py", line 157, in __call_api
    response_data = self.request(
  File "C:\dev\eve_theurgy\swagger_client\api_client.py", line 347, in request
    return self.rest_client.GET(url,
  File "C:\dev\eve_theurgy\swagger_client\rest.py", line 234, in GET
    return self.request("GET", url,
  File "C:\dev\eve_theurgy\swagger_client\rest.py", line 228, in request
    raise ApiException(http_resp=r)
swagger_client.rest.ApiException: (404)
Reason: Not Found

## Response

` {"error":"Not found"}`

### Status Code

`404`

### Headers

Include relevant headers received. Timestamps and request ID is nice, you may not have all these values, fill out what you received (don't worry about headers not listed here, unless pertinent to your issue). E.g.:

```
HTTPHeaderDict({'Date': 'Fri, 04 Dec 2020 06:34:06 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '21', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': 'Content-Type,Authorization,If-None-Match,X-User-Agent', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset', 'Access-Control-Max-Age': '600', 'Content-Language': 'en-us', 'Strict-Transport-Security': 'max-age=31536000', 'Vary': 'Accept-Language', 'X-Esi-Error-Limit-Remain': '99', 'X-Esi-Error-Limit-Reset': '54'})
```

## Expected

# Checklist

Check all boxes that apply to this issue:

- [x ] Bug description is provided
- [x ] Request path is provided
- [x ] Response status code is provided
- [x ] Response headers are provided
- [x ] Response body is provided
- [ ] Expected response is provided

**Comment by Dusty-Meg** [comment] 2020-12-04 06:49
Known issue, CCP took them off deliberately. Should be back today.

Duplicate of #1261

**Closed** 2020-12-04 06:50 UTC

**Comment by michaelphipps** [comment] 2020-12-04 06:52
ESI doesn't return a 503 when an endpoint is down, but you can check if the 404 response header contains "x-esi-request-id".  If it doesn't, it is a strong indicator the service is down.

**Comment by PhenomPBG** [comment] 2020-12-04 07:45
> Known issue, CCP took them off deliberately. Should be back today.
> 
> Duplicate of #1261

Is there a place where this gets announced by CCP?

**Comment by CarbonAlabel** [comment] 2020-12-04 07:49
The #esi channel on Tweetfleet Slack: https://slack.eveisesi.space/
