### ISSUE TITLE
Set destination in game, read from esi

### ISSUE THREAD

**Issue by ezi0o** [esi/esi-issues#1219] opened 2020-07-09 20:57 UTC
# Feature Request

being able to read destination from client

## Use case

hello, today with the current ESI i can, in a 3rd party app, set a destination.
but if i set a destination inside the eve client, i cannot read it through the ESI

## Authentication

no idea

**Comment by ddouglas** [comment] 2020-07-09 20:59
Duplicate of #366

**Closed by ddouglas** 2020-07-09 20:59 UTC
Labels: duplicate, esi-ui
