### ISSUE TITLE
right-to-left unicode character breaks search

### ISSUE THREAD

**Issue by a-tal** [esi/esi-issues#1015] opened 2018-08-24 15:18 UTC
# Bug

Inclusion of the right-to-left invisible unicode character in a search field results in a 500 error.

The right-to-left invisible unicode character is `U+200F`, or `%E2%80%8F` when url encoded.

## Request

`curl -i 'https://esi.evetech.net/v2/search/?strict=false&categories=character&search=hey%E2%80%8F'`

### Status Code

`500`

### Headers

```
date: Fri, 24 Aug 2018 15:10:35 GMT
x-esi-request-id: 301c2e8f-c589-4011-9d90-7320d557f343
```

### Body

```json
{"error":"Unhandled internal error encountered!"}
```

## Expected

`404`

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by tsuthers-ccpgames** [comment] 2019-05-23 15:04
Same root cause as https://github.com/esi/esi-issues/issues/1101 and fixed with the same patch

**Closed by tsuthers-ccpgames** 2019-05-23 15:04 UTC
Labels: bug, esi-search
